---
#Target section
- hosts: webserver
  user: test
  become: yes
  connection: ssh
  gather_facts: no

#Tasks Section

- name: Date/Time when playbook starts
  raw: /usr/bin/data > /home/test/playbookstart.log

- name: Install Apache webserver
  yum:
    pkg: httpd
    status: present
  notify: Restart HTTPD

- name: Webserver Status verification
  shell: service status httpd
  register: output

- debug: var=output

- name: Install telnet
  yum: 
    pkg: telnet
    state: present

- name: Logging all packages installed on the system
  raw: yum list installed > /home/test/installed.log

- name: Date/Time when palybook ends
  raw: /usr/bin/date > /home/test/palybookend.log
  