---
- hosts: webserver
  vars:
    control_server: localhost
    web_root: /var/www/html/
  tasks:
    - name: Install GIT on webservers
      action: yum name=git state=installed update_cache=trueSSS