--- # LOOKUP playbook Example
- hosts: webserver
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - debug: msg="Lookup the super Hero for BRUCE WAYNE {{ lookup('csvfile', 'Wayne file=lookup.csv delimiter=, col=1 default=NOMATCH')}}"