--- # My first YAML playbook for Ansible
# Target Section
- hosts: webserver
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  # Varibale section
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
  # Task section
  tasks:
    - name: Install {{ pkg_git }} on Web Server
      action: yum name={{ pkg_git }} state=installed
    - name: Install telnet on Web Server
      action: yum name=telnet state=installed 
    - name: Install apache on webserver
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
  # Handler Section
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted