--- #Playbook from the outline created
- hosts: webserver
  user: test
  become: yes
  gather_facts: no
  tasks:
    - name: date/time stamp when playbook starts
      command: /usr/bin/date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: install apache web server
      yum: pkg=httpd state=latest
      notify: Start HTTPD
    - name: verify that the webservice is running
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: install client software git
      yum: pkg=git state=latest
    - name: log all the packages installed on the system
      command: yum list installed | grep git
      register: installed_result
    - debug: var=installed_result
    - name: date/time stamp when playbook ends
      command: /usr/bin/date
      register: timestamp_end
    - debug: var=timestamp_end

  handlers:
    - name: Start HTTPD
      service: name=httpd state=restarted
    